version: '3.7'
# https://gist.github.com/cmackenzie1/92e0c3628da6842f0e9ffeca8abbe170
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "${AWS_DYNAMO_LOCAL_PORT}:${AWS_DYNAMO_LOCAL_PORT}"

  dynamodb-admin-local:
    image: aaronshaf/dynamodb-admin
    ports:
      - "${AWS_DYNAMO_ADMIN_PORT}:${AWS_DYNAMO_ADMIN_PORT}"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:${AWS_DYNAMO_LOCAL_PORT}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET}"
    depends_on:
      - dynamodb-local

  dynamodb-admin-dev:
    image: aaronshaf/dynamodb-admin
    ports:
      - "${AWS_DYNAMO_ADMIN_PORT_DEV}:${AWS_DYNAMO_ADMIN_PORT}"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:${AWS_DYNAMO_LOCAL_PORT}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET}"

